### ISSUE TITLE
Unable to import module 'src/handlers/notifications

### ISSUE THREAD

**Issue by jmurabe** [faultline/faultline#40]
日本語で失礼します。
2017-07-31の状態でセットアップを行いました。

faultline-webuiでsample-errors.jsonでの動作確認は出来ましたが、Slackへの通知動作が確認できていない状況です(Incoming WebHooksを作成し、sample-errors.jsonを編集しての動作テスト)

原因を調べていたのですが、callNotificationsで以下のエラーが多数発生していました。

```
Unable to import module 'src/handlers/notifications': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/src/lib/slack.js:12:18)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

```

**Comment by k1LoW** [comment]
Hi @jmurabe .

Have you been using the old faultline and updated to the latest?

> もしかして、古いfaultlineを利用していて最新にアップデートしましたか？

Looking at the error, `url-template` does not seem to be installed.

> エラーを見る限り、`url-tempalte` がインストールされていないように見えます。

Please run `npm run deploy` when you deploy faultline.

> faultlineをデプロイするときは `npm run deploy` を利用すると npm install も実行してくれます

**Comment by jmurabe** [comment]
一度インストール後に削除してのインストールでした。
再度destoryしてdeployしてみましたが、状況は変わりませんでした。

```
08:23:46
Unable to import module 'src/handlers/notifications': Error at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object.<anonymous> (/var/task/src/lib/slack.js:12:18) at Module._compile (module.js:570:32) at Object.Module._extensions..js (module.js
Unable to import module 'src/handlers/notifications': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/src/lib/slack.js:12:18)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
```

deploy時のログ(Serverless: Stack update finished... まで)を添付いたします。

[deploy_log.txt](https://github.com/faultline/faultline/files/1189963/deploy_log.txt)

**Comment by k1LoW** [comment]
Do you use npm5 ( I find `package-lock.json in deploy_log.txt )?
Could you show me Node and npm version.
> npm5を使っているようですね。もしよろしければNodeとnpmのバージョンを教えてもらえますか？

FYI, 
I use Node 6.10.2 & npm 3.10.10 (because AWS Lambda runtime is 6.10). 
And I tested and success using Node 6.10.2 & npm 5.3.0, too just now.
> ちなみに、私はNode 6.10.2 & npm 3.10.10 を利用しています（AWS Lambdaとruntimeを合わせるため）
> また、さきほど npm 5.3.0 でテストをしてみましたがOKでした。

**Comment by jmurabe** [comment]
```
$ npm -v
5.0.3

$ node -v
v8.1.3
```

以上のバージョンでした。
Nodeのバージョンのほうが怪しい気もしますが、まずnpmのバージョンを上げて試してみます。

**Comment by jmurabe** [comment]
```
$ node -v
v6.10.3

$ npm -v
3.10.10

```

deployed with the above version、I received a notification to Slack. Thanks!

> 前記バージョンでデプロイしたところSlackへ通知が来ました。ありがとうございます！

**Comment by k1LoW** [comment]
Yeah!!!! Good!!
